services:  
  alertmanager:
    image: prom/alertmanager:v0.28.1
    container_name: alertmanager
    user: ${MONITORING_UID}:${MONITORING_GID}
    security_opt:
      - no-new-privileges=true
    restart: unless-stopped
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--web.config.file=/etc/alertmanager/web.yml'
      - '--log.level=error'
      - '--storage.path=/alertmanager'
      - '--web.external-url=https://alertmanager.${DOMAIN}'
    labels:
      # logs collection
      logging: promtail
      logging_jobname: containerlogs
      stackname: monitoring

      traefik.enable: true

      # Listen on http, but redirect all requests to https
      traefik.http.routers.alertmanager-http.rule: Host(`alertmanager.${DOMAIN}`)
      traefik.http.routers.alertmanager-http.entrypoints: http
      traefik.http.routers.alertmanager-http.middlewares: redirect-https

      # Direct all https requests to the service, checking with crowdsec first
      traefik.http.routers.alertmanager-https.rule: Host(`alertmanager.${DOMAIN}`)
      traefik.http.routers.alertmanager-https.entrypoints: https
      traefik.http.routers.alertmanager-https.tls: true
      traefik.http.routers.alertmanager-https.tls.certresolver: ${CERT_RESOLVER}
      traefik.http.routers.alertmanager-https.service: alertmanager
      traefik.http.routers.alertmanager-https.middlewares: crowdsec-bouncer

      traefik.http.services.alertmanager.loadbalancer.server.port: 9093

      # network policy
      whalewall.enabled: true
      whalewall.rules: |
        output:
          # DNS
          - proto: udp
            dst_ports:
              - 53
          # HTTP/S
          - proto: tcp
            dst_ports:
              - 80
              - 443
          # reverse proxy
          - network: common_backend
            container: traefik
          # prometheus, loki, grafana: data collection
          - network: common_backend
            container: prometheus
          - network: common_backend
            container: loki
          - network: common_backend
            container: grafana
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1
        tag: "{{.Name}}"
    volumes:
      - type: bind
        source: ./config.yml
        target: /etc/alertmanager/config.yml
        read_only: true
        # Stored encrypted in repo
        x-sops: true
      - type: bind
        source: ./web.yml
        target: /etc/alertmanager/web.yml
        read_only: true
        # Stored encrypted in repo
        x-sops: true
      - alertmanager_data:/alertmanager
    networks:
      - backend

volumes:
  alertmanager_data:
