# COMMON STACK
## Per-stack instances of services (e.g. for backups) are declared here.
services:
  common-backup:
    # https://github.com/lawndoc/stack-back
    image: ghcr.io/lawndoc/stack-back:v1.4.5
    restart: unless-stopped
    container_name: common-backup
    env_file: ./stack-back.env
    labels:
      logging: promtail
      logging_jobname: containerlogs
      stackname: common

      # network policy
      whalewall.enabled: true
      whalewall.rules: |
        output:
          # DNS
          - proto: udp
            dst_ports:
              - 53
          # HTTP/S
          - proto: tcp
            dst_ports:
              - 443
              - 80
          # mariadb backup
          - network: common_backend
            container: mariadb
    volumes: 
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - backup_cache:/cache
      - ${ZFS_POOL_ROOT_HDD}/docker-backups:/backups
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1
        tag: "{{.Name}}"
    networks:
      - backend

networks:
  backend:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: ${DOCKER_HOST_IPV4}
    # Electric Eel default is to allocate a /27 per-app - larger backend pool will be necessary
    ipam:
      config:
        - subnet: ${COMMON_BACKEND_SUBNET_V4}

volumes:
  backup_cache:

include:
  - ./crowdsec/docker-compose.yaml
  - ./nginx/docker-compose.yaml
  - ./portainer/docker-compose.yaml
  - ./traefik/docker-compose.yaml
  - ./whalewall/docker-compose.yaml
