services:
  syncthing:
    # https://github.com/syncthing/syncthing/blob/main/README-Docker.md
    # https://hub.docker.com/r/syncthing/syncthing/tags
    image: syncthing/syncthing:1.29
    container_name: syncthing
    restart: unless-stopped
    environment:
      - PUID=${HOME_UID}
      - PGID=${HOME_GID}
    labels:
      # logs collection
      logging: promtail
      logging_jobname: containerlogs
      stackname: home

      traefik.enable: true

      # Listen on http, but redirect all requests to https
      traefik.http.routers.syncthing-http.rule: Host(`syncthing.${DOMAIN}`)
      traefik.http.routers.syncthing-http.entrypoints: http
      traefik.http.routers.syncthing-http.middlewares: redirect-https

      # Direct all https requests to the service, checking with crowdsec first
      traefik.http.routers.syncthing-https.rule: Host(`syncthing.${DOMAIN}`)
      traefik.http.routers.syncthing-https.entrypoints: https
      traefik.http.routers.syncthing-https.tls: true
      traefik.http.routers.syncthing-https.tls.certresolver: ${CERT_RESOLVER}
      traefik.http.routers.syncthing-https.service: open-webui
      traefik.http.routers.syncthing-https.middlewares: crowdsec-bouncer

      traefik.http.services.open-webui.loadbalancer.server.port: 8384

      # network policy
      whalewall.enabled: true
      whalewall.rules: |
        mapped_ports:
          external:
            allow: true
        output:
          # DNS
          - proto: udp
            dst_ports:
              - 53
          # HTTP/S
          - proto: tcp
            dst_ports:
              - 80
              - 443
          # reverse proxy
          - network: common_backend
            container: traefik
    ports:
      - 22000:22000  # Sync (TCP)
      - 22000:22000/udp  # Sync (QUIC)
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
    volumes:
      - syncthing_data:/var/syncthing
    networks:
      - backend

volumes:
  syncthing_data:
