services:
  tautulli:
    # https://github.com/home-operations/containers/pkgs/container/tautulli
    # https://github.com/Tautulli/Tautulli
    image: ghcr.io/home-operations/tautulli:2.16.0
    container_name: tautulli
    user: ${MEDIA_UID}:${MEDIA_GID}
    security_opt:
      - no-new-privileges=true
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    labels:
      stack-back.volumes: true
      stack-back.volumes.include: "tautulli_config"
      
      # logs collection
      logging: promtail
      logging_jobname: containerlogs
      stackname: media

      traefik.enable: true

      # Listen on http, but redirect all requests to https
      traefik.http.routers.tautulli-http.rule: Host(`tautulli.${DOMAIN}`)
      traefik.http.routers.tautulli-http.entrypoints: http
      traefik.http.routers.tautulli-http.middlewares: redirect-https

      # Direct all https requests to the service, checking with crowdsec first
      traefik.http.routers.tautulli-https.rule: Host(`tautulli.${DOMAIN}`)
      traefik.http.routers.tautulli-https.entrypoints: https
      traefik.http.routers.tautulli-https.tls: true
      traefik.http.routers.tautulli-https.tls.certresolver: ${CERT_RESOLVER}
      traefik.http.routers.tautulli-https.service: tautulli
      traefik.http.routers.tautulli-https.middlewares: crowdsec-bouncer

      traefik.http.services.tautulli.loadbalancer.server.port: 8181

      # network policy
      whalewall.enabled: true
      whalewall.rules: |
        output:
          # DNS
          - proto: udp
            dst_ports:
              - 53
          # HTTP/S
          - proto: tcp
            dst_ports:
              - 80
              - 443
          # Plex
          - proto: tcp
            dst_ports:
              - 32400
          # reverse proxy
          - network: common_backend
            container: traefik
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1
        tag: "{{.Name}}"
    volumes:
      - tautulli_config:/config
    networks:
      - backend

volumes:
  tautulli_config:
