services:
  xteve:
    # https://hub.docker.com/r/dnsforge/xteve
    image: dnsforge/xteve:latest
    container_name: xteve
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    labels:
      # logs collection
      logging: promtail
      logging_jobname: containerlogs
      stackname: media

      traefik.enable: true

      # Listen on http, but redirect all requests to https
      traefik.http.routers.xteve-http.rule: Host(`xteve.${ALT_DOMAIN_RE}`)
      traefik.http.routers.xteve-http.entrypoints: http
      traefik.http.routers.xteve-http.middlewares: redirect-https

      # Direct all https requests to the service, checking with crowdsec first
      traefik.http.routers.xteve-https.rule: Host(`xteve.${ALT_DOMAIN_RE}`)
      traefik.http.routers.xteve-https.entrypoints: https
      traefik.http.routers.xteve-https.tls: true
      traefik.http.routers.xteve-https.tls.certresolver: ${CERT_RESOLVER}
      traefik.http.routers.xteve-https.service: xteve
      traefik.http.routers.xteve-https.middlewares: crowdsec-bouncer

      traefik.http.services.xteve.loadbalancer.server.port: 34400

      # network policy
      whalewall.enabled: true
      whalewall.rules: |
        output:
          # DNS
          - proto: udp
            dst_ports:
              - 53
          # HTTP/S
          - proto: tcp
            dst_ports:
              - 80
              - 443
          # reverse proxy
          - network: common_backend
            container: traefik
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1
        tag: "{{.Name}}"
    volumes:
      - xteve_buffer:/tmp/xteve
      - xteve_config:/home/xteve/conf
      - xteve_guide2go:/home/xteve/guide2go/conf
    networks:
      - backend

volumes:
  xteve_buffer:
  xteve_config:
  xteve_guide2go:
