services:
  xteve:
    restart: unless-stopped
    # https://hub.docker.com/r/alturismo/xteve_guide2go
    # https://github.com/xteve-project/xTeVe
    image: alturismo/xteve_guide2go:latest
    container_name: xteve
    user: ${XTEVE_UID}:${XTEVE_GID}
    labels:
      logging: promtail
      logging_jobname: containerlogs
      stackname: media

      traefik.enable: true

      # Listen on http, but redirect all requests to https
      traefik.http.routers.xteve-http.rule: Host(`xteve.${ALT_DOMAIN_RE}`)
      traefik.http.routers.xteve-http.entrypoints: http
      traefik.http.routers.xteve-http.middlewares: redirect-https

      # Direct all https requests to the service, checking with crowdsec first
      traefik.http.routers.xteve-https.rule: Host(`xteve.${ALT_DOMAIN_RE}`)
      traefik.http.routers.xteve-https.entrypoints: https
      traefik.http.routers.xteve-https.tls: true
      traefik.http.routers.xteve-https.tls.certresolver: ${CERT_RESOLVER}
      traefik.http.routers.xteve-https.service: xteve
      traefik.http.routers.xteve-https.middlewares: crowdsec-bouncer

      traefik.http.services.xteve.loadbalancer.server.port: 34400

      # Enable Whalewall for this service
      whalewall.enabled: true
      # xteve: Communicate with traefik and to WAN over selected protocols.
      whalewall.rules: |
        output:
          - log_prefix: "dns"
            proto: udp
            dst_ports:
              - 53
          - log_prefix: "https"
            proto: tcp
            dst_ports:
              - 443
          - log_prefix: "http"
            proto: tcp
            dst_ports:
              - 80
          # allow communication to traefik
          - network: common_backend
            container: traefik
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1
        tag: "{{.Name}}"
    volumes:
      - xteve_buffer:/tmp/xteve
      - xteve_config:/config
      - xteve_root:/root/.xteve
      - xteve_guide2go:/guide2go
    networks:
      - backend

volumes:
  xteve_buffer:
  xteve_config:
  xteve_root:
  xteve_guide2go:
  
networks:
  backend:
    name: common_backend
    external: true
