services:
  ersatztv:
    image: jasongdove/ersatztv:v0.8.8
    container_name: ersatztv
    restart: unless-stopped
    user: ${MEDIA_UID}:${MEDIA_SHARED_GID}
    environment:
      - TZ=${TZ}
    labels:
      # logs collection
      logging: promtail
      logging_jobname: containerlogs
      stackname: media

      traefik.enable: true

      # Listen on http, but redirect all requests to https
      traefik.http.routers.ersatztv-http.rule: Host(`ersatztv.${DOMAIN}`)
      traefik.http.routers.ersatztv-http.entrypoints: http
      traefik.http.routers.ersatztv-http.middlewares: redirect-https

      # Direct all https requests to the service, checking with crowdsec first, apply basic auth
      traefik.http.routers.ersatztv-https.rule: Host(`ersatztv.${DOMAIN}`)
      traefik.http.routers.ersatztv-https.entrypoints: https
      traefik.http.routers.ersatztv-https.tls: true
      traefik.http.routers.ersatztv-https.tls.certresolver: ${CERT_RESOLVER}
      traefik.http.routers.ersatztv-https.service: ersatztv
      traefik.http.routers.ersatztv-https.middlewares: ersatztv-chain

      # Specific path may pass without basic auth
      traefik.http.routers.ersatztv-https-unauth.rule: Host(`ersatztv.${DOMAIN}`) && PathPrefix(`/iptv`)
      traefik.http.routers.ersatztv-https-unauth.entrypoints: https
      traefik.http.routers.ersatztv-https-unauth.tls: true
      traefik.http.routers.ersatztv-https-unauth.tls.certresolver: ${CERT_RESOLVER}
      traefik.http.routers.ersatztv-https-unauth.service: ersatztv
      traefik.http.routers.ersatztv-https-unauth.middlewares: crowdsec-bouncer

      # Basic auth middleware
      traefik.http.middlewares.ersatztv-auth.basicauth.users: ${ERSATZTV_USER}:${ERSATZTV_PASSWORD_HASH}
      
      # Chain middlewares including basic auth
      traefik.http.middlewares.ersatztv-chain.chain.middlewares: crowdsec-bouncer,ersatztv-auth

      traefik.http.services.ersatztv.loadbalancer.server.port: 8409

      # network policy
      whalewall.enabled: true
      whalewall.rules: |
        output:
          # DNS
          - proto: udp
            dst_ports:
              - 53
          # HTTP/S
          - proto: tcp
            dst_ports:
              - 80
              - 443
          # reverse proxy
          - network: common_backend
            container: traefik
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1
        tag: "{{.Name}}"
    volumes:
      - ersatztv_config:/config
      - ersatztv_transcode:/transcode
      - ${ZFS_POOL_ROOT_HDD}/media/music_videos:/data/music_videos:ro
    networks:
      - backend

volumes:
  ersatztv_config:
  ersatztv_transcode:
