# https://getsops.io/docs/#using-sopsyaml-conf-to-select-kms-pgp-and-age-for-new-files
creation_rules:
    - path_regex: .*/tn/.*
      age: 'age1hgayx0xta2t248c8xhu2pex68z5tqak5487es2m7ccp5gjducanq0egash'
