services:
  couchdb:
    # https://hub.docker.com/_/couchdb
    image: couchdb:3.4.3
    container_name: couchdb
    restart: unless-stopped
    user: ${HOME_UID}:${HOME_GID}
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    labels:
      # logs collection
      logging: promtail
      logging_jobname: containerlogs
      stackname: home

      traefik.enable: true

      # Listen on http, but redirect all requests to https
      traefik.http.routers.ols-http.rule: Host(`ols.${ALT_DOMAIN_HOME}`)
      traefik.http.routers.ols-http.entrypoints: http
      traefik.http.routers.ols-http.middlewares: redirect-https

      # Direct all https requests to the service with ols-specific middleware
      traefik.http.routers.ols-https.rule: Host(`ols.${ALT_DOMAIN_HOME}`)
      traefik.http.routers.ols-https.entrypoints: https
      traefik.http.routers.ols-https.tls: true
      traefik.http.routers.ols-https.tls.certresolver: ${CERT_RESOLVER}
      traefik.http.routers.ols-https.service: ols
      traefik.http.routers.ols-https.middlewares: ols-chain


      # Middleware for CouchDB-specific CORS configuration
      traefik.http.middlewares.obsidiancors.headers.accesscontrolallowmethods: GET,PUT,POST,HEAD,DELETE
      traefik.http.middlewares.obsidiancors.headers.accesscontrolallowheaders: accept,authorization,content-type,origin,referer
      traefik.http.middlewares.obsidiancors.headers.accesscontrolalloworiginlist: app://obsidian.md,capacitor://localhost,http://localhost
      traefik.http.middlewares.obsidiancors.headers.accesscontrolmaxage: 3600
      traefik.http.middlewares.obsidiancors.headers.addvaryheader: true
      traefik.http.middlewares.obsidiancors.headers.accessControlAllowCredentials: true

      # Chain all ols middlewares together
      traefik.http.middlewares.ols-chain.chain.middlewares: crowdsec-bouncer, obsidiancors

      traefik.http.services.ols.loadbalancer.server.port: 5984

      # network policy
      whalewall.enabled: true
      whalewall.rules: |
        output:
          # DNS
          - proto: udp
            dst_ports:
              - 53
          # HTTP/S
          - proto: tcp
            dst_ports:
              - 80
              - 443
          # reverse proxy
          - network: common_backend
            container: traefik   
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1
        tag: "{{.Name}}"

    volumes:
      - couchdb_data:/opt/couchdb/data
      - ./local.ini:/opt/couchdb/etc/local.ini:ro
    networks:
      - backend

volumes:
  couchdb_data:
