services:
  nextpvr:
    # https://hub.docker.com/r/nextpvr/nextpvr_amd64
    # https://github.com/sub3/NextPVR/wiki/Install-Docker
    image: nextpvr/nextpvr_amd64:stable
    container_name: nextpvr
    user: ${MEDIA_UID}:${MEDIA_SHARED_GID}
    security_opt:
      - no-new-privileges=true
    restart: unless-stopped
    labels:
      stack-back.volumes: true
      stack-back.volumes.include: "nextpvr_config"
      
      # Enable log collection via Promtail
      logging: promtail
      logging_jobname: containerlogs
      stackname: media

      traefik.enable: true

      # Listen on http, but redirect all requests to https
      traefik.http.routers.nextpvr-http.rule: Host(`nextpvr.${DOMAIN}`)
      traefik.http.routers.nextpvr-http.entrypoints: http
      traefik.http.routers.nextpvr-http.middlewares: redirect-https

      # Direct all https requests to the service, checking with crowdsec first
      traefik.http.routers.nextpvr-https.rule: Host(`nextpvr.${DOMAIN}`)
      traefik.http.routers.nextpvr-https.entrypoints: https
      traefik.http.routers.nextpvr-https.tls: true
      traefik.http.routers.nextpvr-https.tls.certresolver: ${CERT_RESOLVER}
      traefik.http.routers.nextpvr-https.service: nextpvr
      traefik.http.routers.nextpvr-https.middlewares: crowdsec-bouncer

      traefik.http.services.nextpvr.loadbalancer.server.port: 8866

      # network policy
      whalewall.enabled: true
      whalewall.rules: |
        output:
          # DNS
          - proto: udp
            dst_ports:
              - 53
          # HTTP/S
          - proto: tcp
            dst_ports:
              - 80
              - 443
          # reverse proxy
          - network: common_backend
            container: traefik
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1
        tag: "{{.Name}}"
    volumes:
      - nextpvr_config:/config
      - nextpvr_buffer:/buffer
      - ${ZFS_POOL_ROOT_HDD}/media/nextpvr_recordings:/recordings
    networks:
      - backend

volumes:
  nextpvr_buffer:
  nextpvr_config:
