services:
  promtail:
    image:  grafana/promtail:3.5.2
    container_name: promtail
    restart: unless-stopped
    command: -config.file=/etc/promtail/docker-config.yml
    labels:
      # logs collection
      logging: promtail
      logging_jobname: containerlogs
      stackname: monitoring

      # network policy
      whalewall.enabled: true
      whalewall.rules: |
        output:
          # loki: data collection
          - network: common_backend
            container: loki
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1
        tag: "{{.Name}}"
    volumes:
      - ./docker-config.yml:/etc/promtail/docker-config.yml:ro
      - ${DOCKER_DATA_ROOT}/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - backend
