networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: ${COMMON_BACKEND_SUBNET_V4}

include:
  - ./crowdsec/docker-compose.yaml
  - ./nginx/docker-compose.yaml
  - ./portainer/docker-compose.yaml
  - ./traefik/docker-compose.yaml
  - ./whalewall/docker-compose.yaml
