services:
  ownfoil:
    # https://hub.docker.com/r/a1ex4/ownfoil/tags
    image: a1ex4/ownfoil:1.2.3
    container_name: ownfoil
    restart: unless-stopped
    environment:
      # https://github.com/a1ex4/ownfoil/tree/v1#docker-compose
      - PUID=${HINOX_UID}
      - PGID=${HINOX_GID}
      - USERNAME=${HINOX_USER}
      - PASSWORD=${HINOX_PASSWORD}
      - SAVE_ENABLED=false
    labels:
      # logs collection
      logging: promtail
      logging_jobname: containerlogs
      stackname: xfer

      traefik.enable: true

      # Listen on http, but redirect all requests to https
      traefik.http.routers.ownfoil-http.rule: Host(`hinox.${DOMAIN}`)
      traefik.http.routers.ownfoil-http.entrypoints: http
      traefik.http.routers.ownfoil-http.middlewares: redirect-https

      # Direct all https requests to the service, checking with crowdsec first
      traefik.http.routers.ownfoil-https.rule: Host(`hinox.${DOMAIN}`)
      traefik.http.routers.ownfoil-https.entrypoints: https
      traefik.http.routers.ownfoil-https.tls: true
      traefik.http.routers.ownfoil-https.tls.certresolver: ${CERT_RESOLVER}
      traefik.http.routers.ownfoil-https.service: ownfoil
      traefik.http.routers.ownfoil-https.middlewares: crowdsec-bouncer

      traefik.http.services.ownfoil.loadbalancer.server.port: 80

      # network policy
      whalewall.enabled: true
      whalewall.rules: |
        output:
          # DNS
          - proto: udp
            dst_ports:
              - 53
          # HTTP/S
          - proto: tcp
            dst_ports:
              - 443
              - 80
          # reverse proxy
          - network: common_backend
            container: traefik
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1
        tag: "{{.Name}}"
    volumes:
      - ${GAMES_ROOT}:/games
    networks:
      - backend
