services:
  sonarr:
    # https://github.com/onedr0p/containers/pkgs/container/sonarr
    # https://github.com/Sonarr/Sonarr
    image: ghcr.io/onedr0p/sonarr:4.0.11
    user: ${SONARR_UID}:${MEDIA_SHARED_GID}
    security_opt:
      - no-new-privileges=true
    container_name: sonarr
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    labels:
      # logs collection
      logging: promtail
      logging_jobname: containerlogs
      stackname: media

      traefik.enable: true

      # Listen on http, but redirect all requests to https
      traefik.http.routers.sonarr-http.rule: Host(`sonarr.${DOMAIN}`)
      traefik.http.routers.sonarr-http.entrypoints: http
      traefik.http.routers.sonarr-http.middlewares: redirect-https

      # Direct all https requests to the service, checking with crowdsec first
      traefik.http.routers.sonarr-https.rule: Host(`sonarr.${DOMAIN}`)
      traefik.http.routers.sonarr-https.entrypoints: https
      traefik.http.routers.sonarr-https.tls: true
      traefik.http.routers.sonarr-https.tls.certresolver: ${CERT_RESOLVER}
      traefik.http.routers.sonarr-https.service: sonarr
      traefik.http.routers.sonarr-https.middlewares: crowdsec-bouncer

      traefik.http.services.sonarr.loadbalancer.server.port: 8989

      # network policy
      whalewall.enabled: true
      whalewall.rules: |
        output:
          # DNS
          - proto: udp
            dst_ports:
              - 53
          # HTTP/S
          - proto: tcp
            dst_ports:
              - 80
              - 443
          # reverse proxy
          - network: common_backend
            container: traefik
          # metrics collection
          - network: common_backend
            container: sonarr-exporter
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1
        tag: "{{.Name}}"
    volumes:
      - sonarr_config:/config
      - ${ZFS_POOL_ROOT_HDD}/media:/data
    networks:
      - backend

  sonarr-exporter:
    # https://github.com/onedr0p/exportarr
    image: ghcr.io/onedr0p/exportarr:v2.0.1
    container_name: sonarr-exporter
    user: ${MEDIA_UID}:${MEDIA_GID}
    security_opt:
      - no-new-privileges=true
    restart: unless-stopped
    command: ["sonarr"]
    environment:
      # https://github.com/onedr0p/exportarr#configuration
      - PORT=9707
      - URL=http://sonarr:8989
      - APIKEY=${SONARR_API_KEY}
    labels:
      # logs collection
      logging: promtail
      logging_jobname: containerlogs
      stackname: media
      
      # network policy
      whalewall.enabled: true
      whalewall.rules: |
        output:
          # metrics collection
          - network: common_backend
            container: sonarr
          # metrics scrape
          - network: common_backend
            container: prometheus
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1
        tag: "{{.Name}}"
    networks:
      - backend

volumes:
  sonarr_config:
