services:
  crowdsec:
    image: crowdsecurity/crowdsec:v1.6.3
    container_name: crowdsec
    restart: unless-stopped
    environment:
      # https://hub.docker.com/r/crowdsecurity/crowdsec
      - TZ=${TZ}
      # https://app.crowdsec.net/hub/collections
      - COLLECTIONS=crowdsecurity/traefik crowdsecurity/http-cve
    labels:
      # Enable Whalewall for this service
      whalewall.enabled: true
      # crowdsec: communicate with traefik and to WAN over selected protocols.
      whalewall.rules: |
        output:
          - log_prefix: "dns"
            proto: udp
            dst_ports:
              - 53
          - log_prefix: "https"
            proto: tcp
            dst_ports:
              - 443
          - log_prefix: "http"
            proto: tcp
            dst_ports:
              - 80
          # allow communication to traefik
          - network: common_backend
            container: traefik
    volumes:
      - crowdsec_log:/var/log/crowdsec
      - crowdsec_data:/var/lib/crowdsec/data
      - crowdsec_config:/etc/crowdsec
      # Allow Crowdsec to read and parse Traefik access logs
      - traefik_log:/var/log/traefik:ro
    networks:
      - backend

volumes:
  crowdsec_log:
  crowdsec_config:
  crowdsec_data:
