services:
  crowdsec:
    image: crowdsecurity/crowdsec:v1.6.8
    container_name: crowdsec
    user: ${COMMON_UID}:${COMMON_GID}
    security_opt:
      - no-new-privileges=true
    restart: unless-stopped
    environment:
      # https://hub.docker.com/r/crowdsecurity/crowdsec
      - TZ=${TZ}
      # https://app.crowdsec.net/hub/collections
      - COLLECTIONS=crowdsecurity/traefik crowdsecurity/http-cve
    labels:
      logging: promtail
      logging_jobname: containerlogs
      stackname: common

      # network policy
      whalewall.enabled: true
      whalewall.rules: |
        output:
          # DNS
          - proto: udp
            dst_ports:
              - 53
          # HTTP/S
          - proto: tcp
            dst_ports:
              - 443
              - 80
          # reverse proxy
          - network: common_backend
            container: traefik
          # metrics collection
          - network: common_backend
            container: prometheus
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1
        tag: "{{.Name}}"
    volumes:
      - crowdsec_log:/var/log/crowdsec
      - crowdsec_data:/var/lib/crowdsec/data
      - crowdsec_config:/etc/crowdsec
      # Allow Crowdsec to read and parse Traefik access logs
      - traefik_log:/var/log/traefik:ro
    networks:
      - backend

volumes:
  crowdsec_log:
  crowdsec_config:
  crowdsec_data:
