server: ENC[AES256_GCM,data:Nhedc9XRRF+93z3rf409fRqgsUJAsv+Nc/klnVA=,iv:JeK62fwsi54SPFBY04UZIOOw4ejiX1vqV25uTnuvjYw=,tag:EwF2wcd2CJ0zJHNyuKiGeg==,type:str]
authToken: ENC[AES256_GCM,data:rFc05ynZZKyFQgmNEIUBNy00Nqe3SUZ2bvXfhvpd9PM=,iv:ZRna7PUuobe/hzbg6iq3W9FjZp7OVExV7J1TRHyhXzU=,tag:QI7FggfWNADHV96QTZZzBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hgayx0xta2t248c8xhu2pex68z5tqak5487es2m7ccp5gjducanq0egash
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NmdRV1JPQklIdzhrajVX
            WUo0Y2gxWmZOM1pSVVl3dDNJRGtxMENnOVFFCmMvd2FBOFVQdzZVbEFWdHptbFFn
            cXVKb3JPVXRla1hJRVo1bHlVamw2ZTAKLS0tIG5JK2RBQWZrcHY2Ny9STC95MEhv
            dVlnWVplcmVPTTZ3LzlrNU91Skh5V2sKPt3gbXzAOT8it3ZdPETFjt2SQ4Vx88wW
            0toWrIlqAVWeLuqN8iBSAZIxZiLQDWNjGSQeRXauwGThnTzrSwc8ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-31T03:49:47Z"
    mac: ENC[AES256_GCM,data:qkWfjtRVaUvMgpWJxo36uBG+39p0hXbDFz94kL17gZ/ySy9VKvoq+0Whr4G1mFm3s4O5Eh074gikzUfYgw33ccsqxhk6mLKMGtocPeY9QB/1JlEL2g0AjumFpFhEDw8ap/WCeDUlrPQbVLDKQ2w37qT+PF5P1YPq1U+18rEE5Q4=,iv:sY4YfWQ82IpvtRRmAAAvAOjQ68cM+ts1czkOTumXxag=,tag:CR/onwkTAURnW5Mzjr4bkQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
