services:
  streammaster:
    # https://hub.docker.com/r/senexcrenshaw/streammaster/tags
    # https://github.com/SenexCrenshaw/StreamMaster
    image: senexcrenshaw/streammaster:main-1.0.1.7
    container_name: streammaster
    restart: unless-stopped
    environment:
      - PUID=${MEDIA_UID}
      - PGID=${MEDIA_GID}
      - POSTGRES_USER_FILE=/var/run/secrets/streammaster-postgres-user
      - POSTGRES_PASSWORD_FILE=/var/run/secrets/streammaster-postgres-password

      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    secrets:
      - streammaster-postgres-user
      - streammaster-postgres-password
    labels:
      # logs collection
      logging: promtail
      logging_jobname: containerlogs
      stackname: media

      # network policy
      whalewall.enabled: true
      whalewall.rules: |
        output:
          # DNS
          - proto: udp
            dst_ports:
              - 53
          # HTTP/S
          - proto: tcp
            dst_ports:
              - 443
              - 80
          # reverse proxy
          - network: common_backend
            container: traefik
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1
        tag: "{{.Name}}"
    volumes:
      - streammaster_config:/config
    network_mode: "service:streammaster-gluetun"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  streammaster-gluetun:
    image: qmcgaw/gluetun:v3.40.0
    container_name: streammaster-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=${STREAMMASTER_GLUETUN_PROVIDER}
      - VPN_TYPE=${STREAMMASTER_GLUETUN_TYPE}
      - WIREGUARD_PRIVATE_KEY=${STREAMMASTER_GLUETUN_WG_PRIVATE_KEY}
      - SERVER_COUNTRIES=${STREAMMASTER_GLUETUN_COUNTRIES}
      - SERVER_CITIES=${STREAMMASTER_GLUETUN_CITIES}
    labels:
      # logs collection
      logging: promtail
      logging_jobname: containerlogs
      stackname: media

      traefik.enable: true

      # Listen on http, but redirect all requests to https
      traefik.http.routers.streammaster-http.rule: Host(`streammaster.${DOMAIN}`)
      traefik.http.routers.streammaster-http.entrypoints: http
      traefik.http.routers.streammaster-http.middlewares: redirect-https

      # Direct all https requests to the service, checking with crowdsec first
      traefik.http.routers.streammaster-https.rule: Host(`streammaster.${DOMAIN}`)
      traefik.http.routers.streammaster-https.entrypoints: https
      traefik.http.routers.streammaster-https.tls: true
      traefik.http.routers.streammaster-https.tls.certresolver: ${CERT_RESOLVER}
      traefik.http.routers.streammaster-https.service: streammaster
      traefik.http.routers.streammaster-https.middlewares: streammaster-chain

      # Middleware to redirect local testing url patterns
      traefik.http.middlewares.streammaster-redirectregex.redirectregex.permanent: true
      traefik.http.middlewares.streammaster-redirectregex.redirectregex.regex: 'https://(.*)/s/(.*)'
      traefik.http.middlewares.streammaster-redirectregex.redirectregex.replacement: 'https://$${1}'

      # Chain all middlewares together
      traefik.http.middlewares.streammaster-chain.chain.middlewares: crowdsec-bouncer, streammaster-redirectregex

      traefik.http.services.streammaster.loadbalancer.server.port: 7095

    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1
        tag: "{{.Name}}"
    networks:
      - backend

  streammaster-watchdog:
    image: sergeantpanda/streammasterwatchdog:1.1.3
    container_name: streammaster-watchdog
    user: ${MEDIA_UID}:${MEDIA_GID}
    security_opt:
      - no-new-privileges=true
    environment:
      - SERVER_URL=http://streammaster:7095
      - USERNAME=${STREAMMASTER_USERNAME}
      - PASSWORD=${STREAMMASTER_PASSWORD}
      - TZ=${TZ}
    restart: unless-stopped
    labels:
      # logs collection
      logging: promtail
      logging_jobname: containerlogs
      stackname: media

      # network policy
      whalewall.enabled: true
      whalewall.rules: |
        output:
          # streammaster api
          - network: common_backend
            container: streammaster
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1
        tag: "{{.Name}}"
    networks:
      - backend

secrets:
  streammaster-postgres-user:
    file: ./postgres-user.txt
  streammaster-postgres-password:
    file: ./postgres-password.txt

volumes:
  streammaster_config:
