services:
  emby:
    restart: unless-stopped
    # https://hub.docker.com/r/emby/embyserver
    # https://github.com/MediaBrowser/Emby.Releases/releases
    image: emby/embyserver:4.8.10.0
    container_name: emby
    # runtime: nvidia
    environment:
      - UID=${EMBY_UID}
      - GID=${MEDIA_GID}
    labels:
      logging: promtail
      logging_jobname: containerlogs
      stackname: media

      traefik.enable: true

      # Listen on http, but redirect all requests to https
      traefik.http.routers.emby-http.rule: Host(`emby.${DOMAIN}`)
      traefik.http.routers.emby-http.entrypoints: http
      traefik.http.routers.emby-http.middlewares: redirect-https

      # Direct all https requests to the service, checking with crowdsec first
      traefik.http.routers.emby-https.rule: Host(`emby.${DOMAIN}`)
      traefik.http.routers.emby-https.entrypoints: https
      traefik.http.routers.emby-https.tls: true
      traefik.http.routers.emby-https.tls.certresolver: ${CERT_RESOLVER}
      traefik.http.routers.emby-https.service: emby
      traefik.http.routers.emby-https.middlewares: crowdsec-bouncer

      traefik.http.services.emby.loadbalancer.server.port: 32800

      # Enable Whalewall for this service
      whalewall.enabled: true
      # emby: allow published ports inbound. Communicate with traefik and to WAN over selected protocols.
      whalewall.rules: |
        mapped_ports:
          external:
            allow: true
        output:
          - log_prefix: "dns"
            proto: udp
            dst_ports:
              - 53
          - log_prefix: "https"
            proto: tcp
            dst_ports:
              - 443
          - log_prefix: "http"
            proto: tcp
            dst_ports:
              - 80
          # allow communication to traefik
          - network: common_backend
            container: traefik
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1
        tag: "{{.Name}}"
    ports:
      - 32800:32800 # http
      - 32900:32900 # https
    # devices:
      # NVENC/NVDEC
      # - /dev/dri
    volumes:
      - emby_config:/config
      - ${ZFS_POOL_ROOT_HDD}/media/tv:/data/tv:ro
      - ${ZFS_POOL_ROOT_HDD}/media/movies:/data/movies:ro
      - ${ZFS_POOL_ROOT_HDD}/media/dvr:/data/dvr
    networks:
      - backend

  emby-exporter:
    restart: unless-stopped
    # https://github.com/TOomaAh/emby_exporter_go
    image: bagul/goemby_exporter:v1.0.11
    container_name: emby-exporter
    environment:
      - CONFIG_FILE=/config/config.yaml
      - TZ=${TZ}
    labels:
      logging: promtail
      logging_jobname: containerlogs
      stackname: media

      whalewall.enabled: true
      whalewall.rules: |
        output:
          - network: common_backend
            container: emby
          - network: common_backend
            container: prometheus
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1
        tag: "{{.Name}}"
    volumes:
      - ./emby_exporter_config.yaml:/config/config.yaml
    networks:
      - backend

volumes:
  emby_config:

networks:
  backend:
    name: common_backend
    external: true
