services:
  emby:
    # https://hub.docker.com/r/emby/embyserver
    # https://github.com/MediaBrowser/Emby.Releases/releases
    image: emby/embyserver:4.8.10.0
    container_name: emby
    restart: unless-stopped
    environment:
      - UID=${EMBY_UID}
      - GID=${MEDIA_SHARED_GID}
      
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    labels:
      # logs collection
      logging: promtail
      logging_jobname: containerlogs
      stackname: media

      traefik.enable: true

      # Listen on http, but redirect all requests to https
      traefik.http.routers.emby-http.rule: Host(`emby.${DOMAIN}`)
      traefik.http.routers.emby-http.entrypoints: http
      traefik.http.routers.emby-http.middlewares: redirect-https

      # Direct all https requests to the service, checking with crowdsec first
      traefik.http.routers.emby-https.rule: Host(`emby.${DOMAIN}`)
      traefik.http.routers.emby-https.entrypoints: https
      traefik.http.routers.emby-https.tls: true
      traefik.http.routers.emby-https.tls.certresolver: ${CERT_RESOLVER}
      traefik.http.routers.emby-https.service: emby
      traefik.http.routers.emby-https.middlewares: crowdsec-bouncer

      traefik.http.services.emby.loadbalancer.server.port: 32800

      # network policy
      whalewall.enabled: true
      whalewall.rules: |
        mapped_ports:
          external:
            allow: true
        output:
          # DNS
          - proto: udp
            dst_ports:
              - 53
          # HTTP/S
          - proto: tcp
            dst_ports:
              - 80
              - 443
          # reverse proxy
          - network: common_backend
            container: traefik
          # metrics collection
          - network: common_backend
            container: emby-exporter
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1
        tag: "{{.Name}}"
    ports:
      - 32800:32800 # http
      - 32900:32900 # https
    volumes:
      - emby_config:/config
      # constrain due to s6
      - ${ZFS_POOL_ROOT_HDD}/media/tv:/data/tv:ro
      - ${ZFS_POOL_ROOT_HDD}/media/movies:/data/movies:ro
      - ${ZFS_POOL_ROOT_HDD}/media/emby_recordings:/recordings
    networks:
      - backend
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  emby_config:
