services:
  node-exporter:
    image: prom/node-exporter:v1.8.2
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude'
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    networks:
      - backend
    labels:
      logging: promtail
      logging_jobname: containerlogs
      stackname: monitoring

      # Enable Whalewall for this service
      whalewall.enabled: true
      # loki: Communicate with monitoring data sources.
      whalewall.rules: |
        output:
          # prometheus: data collection
          - network: common_backend
            container: prometheus

    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1
        tag: "{{.Name}}"

networks:
  backend:
    name: common_backend
    external: true
