services:
  loki:
    image: grafana/loki:3.2.1
    container_name: loki
    user: ${MONITORING_UID}:${MONITORING_GID}
    command: -config.file=/etc/loki/loki.yaml
    volumes:
      - ./loki.yaml:/etc/loki/loki.yaml:ro
      - ./rules.yaml:/etc/loki/rules/fake/loki-rules.yml:ro
    networks:
      - backend
    labels:
      logging: promtail
      logging_jobname: containerlogs
      stackname: monitoring

      # Enable Whalewall for this service
      whalewall.enabled: true
      # loki: Communicate with monitoring data sources.
      whalewall.rules: |
        output:
          # prometheus, grafana, alertmanager, promtail: data collection
          - network: common_backend
            container: prometheus
          - network: common_backend
            container: grafana
          - network: common_backend
            container: alertmanager
          - network: common_backend
            container: promtail

    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1
        tag: "{{.Name}}"
