services:
  cadvisor:
    # https://github.com/google/cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.50.0
    container_name: cadvisor
    restart: unless-stopped
    command:
      # https://github.com/google/cadvisor/blob/master/docs/running.md#with-docker
      # https://github.com/google/cadvisor/issues/3139
      - --disable_metrics=process,referenced_memory
      # https://github.com/google/cadvisor/issues/2523
      - --docker_only=true
      - --housekeeping_interval=10s

    volumes:
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - ${DOCKER_DATA_ROOT}:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
    ports:
      # fallback internal
      - 8080:8080
    networks:
      - backend
    labels:
      logging: promtail
      logging_jobname: containerlogs
      stackname: monitoring

      # Enable Whalewall for this service
      whalewall.enabled: true
      # cadvisor: Allow published ports inbound. Communicate with monitoring data sources.
      whalewall.rules: |
        mapped_ports:
          external:
            allow: true
        output:
          # prometheus: data collection
          - network: common_backend
            container: prometheus

    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1
        tag: "{{.Name}}"

networks:
  backend:
    name: common_backend
    external: true
