services:
  cadvisor:
    # https://github.com/google/cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.52.1
    container_name: cadvisor
    restart: unless-stopped
    command:
      # https://github.com/google/cadvisor/blob/master/docs/running.md#with-docker
      # https://github.com/google/cadvisor/issues/3139
      - --enable_metrics=cpu,cpuLoad,disk,diskIO,memory,network
      # https://github.com/google/cadvisor/issues/2523
      - --docker_only=true
      - --housekeeping_interval=10s
    labels:
      # logs collection
      logging: promtail
      logging_jobname: containerlogs
      stackname: monitoring

      # network policy
      whalewall.enabled: true
      whalewall.rules: |
        output:
          # metrics scrape
          - network: common_backend
            container: prometheus
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1
        tag: "{{.Name}}"
    volumes:
      # Adjusted to enable specific metrics above
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /proc:/rootfs/proc:ro
      - /dev/disk:/dev/disk:ro
      - /etc/machine-id:/rootfs/etc/machine-id:ro
      - ${DOCKER_DATA_ROOT}/containers:/rootfs/${DOCKER_DATA_ROOT}/containers:ro
      - ${DOCKER_DATA_ROOT}/overlay2:/rootfs/${DOCKER_DATA_ROOT}/overlay2:ro
      - ${DOCKER_DATA_ROOT}/image:/rootfs/${DOCKER_DATA_ROOT}/image:ro
    networks:
      - backend
