services:
  cadvisor:
    # https://github.com/google/cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.50.0
    container_name: cadvisor
    restart: unless-stopped
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /mnt/.ix-apps/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
    networks:
      - backend
    labels:
      logging: promtail
      logging_jobname: containerlogs
      stackname: monitoring
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1
        tag: "{{.Name}}"

networks:
  backend:
    name: common_backend
    external: true

# TODO:
