services:
  deluge:
    # https://github.com/linuxserver/docker-deluge/pkgs/container/deluge
    image: lscr.io/linuxserver/deluge:2.1.1
    container_name: deluge
    restart: unless-stopped
    environment:
      # https://docs.linuxserver.io/images/docker-deluge/#environment-variables-e
      - PUID=${DELUGE_UID}
      - PGID=${DELUGE_GID}
      - TZ=${TZ}
    labels:
      traefik.enable: true

      # Listen on http, but redirect all requests to https
      traefik.http.routers.deluge-http.rule: Host(`deluge.${DOMAIN}`)
      traefik.http.routers.deluge-http.entrypoints: http
      traefik.http.routers.deluge-http.middlewares: redirect-https

      # Direct all https requests to the service, checking with crowdsec first
      traefik.http.routers.deluge-https.rule: Host(`deluge.${DOMAIN}`)
      traefik.http.routers.deluge-https.entrypoints: https
      traefik.http.routers.deluge-https.tls: true
      traefik.http.routers.deluge-https.tls.certresolver: ${CERT_RESOLVER}
      traefik.http.routers.deluge-https.service: deluge
      traefik.http.routers.deluge-https.middlewares: crowdsec-bouncer

      traefik.http.services.deluge.loadbalancer.server.port: 8112
    ports:
      # Bittorrent inbound
      - 31727:31727
      - 31727:31727/udp
    volumes:
      - deluge_config:/config
      - ${DOWNLOADS_ROOT}:/downloads
    networks:
      - backend

volumes:
  deluge_config:
