cli -c 'account group create gid=1002 name=media smb=true'
cli -c 'account group create gid=4001 name=sonarr smb=false'
cli -c 'account group create gid=4002 name=radarr smb=false'
cli -c 'account group create gid=4003 name=sabnzbd smb=false'
cli -c 'account group create gid=4004 name=navidrome smb=false'
cli -c 'account group create gid=4005 name=plex smb=false'
cli -c 'account group create gid=4006 name=emby smb=false'
cli -c 'account group create gid=4007 name=tautulli smb=false'
cli -c 'account user create username=sonarr full_name=sonarr uid=4001 group_create=false home_create=false password_disabled=true home=/var/empty group=sonarr groups=media smb=false shell=/usr/sbin/nologin'
cli -c 'account user create username=radarr full_name=radarr uid=4002 group_create=false home_create=false password_disabled=true home=/var/empty group=radarr groups=media smb=false shell=/usr/sbin/nologin'
cli -c 'account user create username=sabnzbd full_name=sabnzbd uid=4003 group_create=false home_create=false password_disabled=true home=/var/empty group=sabnzbd groups=media smb=false shell=/usr/sbin/nologin'
cli -c 'account user create username=navidrome full_name=navidrome uid=4004 group_create=false home_create=false password_disabled=true home=/var/empty group=navidrome groups=media smb=false shell=/usr/sbin/nologin'
cli -c 'account user create username=plex full_name=plex uid=4005 group_create=false home_create=false password_disabled=true home=/var/empty group=plex groups=media smb=false shell=/usr/sbin/nologin'
cli -c 'account user create username=emby full_name=emby uid=4006 group_create=false home_create=false password_disabled=true home=/var/empty group=emby groups=media smb=false shell=/usr/sbin/nologin'
cli -c 'account user create username=tautulli full_name=tautulli uid=4007 group_create=false home_create=false password_disabled=true home=/var/empty group=tautulli smb=false shell=/usr/sbin/nologin'
