# MEDIA STACK
## Per-stack instances of services (e.g. for backups) are declared here.
services:
  media-backup:
    restart: unless-stopped
    # https://github.com/offen/docker-volume-backup    
    image: offen/docker-volume-backup:v2.43.3
    container_name: media-backup
    environment:
      # https://offen.github.io/docker-volume-backup/reference
      - BACKUP_FILENAME=media-%Y-%m-%dT%H-%M-%S.tar.gz
      - BACKUP_CRON_EXPRESSION=40 1 * * *
      - BACKUP_PRUNING_PREFIX=media-
      - BACKUP_RETENTION_DAYS=7
    labels:
      logging: promtail
      logging_jobname: containerlogs
      stackname: media

      # network policy
      whalewall.enabled: true
      # backup: no traffic in or out
    volumes: 
      # Backup source volumes
      # emby
      - emby_config:/backup/emby_config:ro
      # ersatztv
      - ersatztv_config:/backup/ersatztv_config:ro
      # navidrome
      - navidrome_data:/backup/navidrome_data:ro
      # nextpvr
      - nextpvr_config:/backup/nextpvr_config:ro
      # plex
      - plex_config:/backup/plex_config:ro
      # radarr
      - radarr_config:/backup/radarr_config:ro
      # sabnzbd
      - sabnzbd_config:/backup/sabnzbd_config:ro
      # sonarr
      - sonarr_config:/backup/sonarr_config:ro
      # streammaster
      - streammaster_config:/backup/streammaster_config:ro
      # tautulli
      - tautulli_config:/backup/tautulli_config:ro

      # Backup target
      - ${ZFS_POOL_ROOT_HDD}/docker-backups:/archive
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1
        tag: "{{.Name}}"
    networks:
      - backend

# When referring to a network called 'backend', we mean the common stack's backend network
networks:
  backend:
    name: common_backend
    external: true

# Remaining services in the stack have their own Compose configuration.
include:
  - ./emby/docker-compose.yaml
  - ./ersatztv/docker-compose.yaml
  - ./navidrome/docker-compose.yaml
  - ./nextpvr/docker-compose.yaml
  - ./plex/docker-compose.yaml
  - ./radarr/docker-compose.yaml
  - ./sabnzbd/docker-compose.yaml
  - ./sonarr/docker-compose.yaml
  - ./streammaster/docker-compose.yaml
  - ./tautulli/docker-compose.yaml
